### ISSUE TITLE
Include config files for Fast-as-Fabric in code.

### ISSUE THREAD

**Issue by Sirbucket** [IronOxidizer/FastAsFabric#5] opened 2021-06-08 22:24 UTC
To improve workflow it may be worth something to add the config files to github so changes can be made with support.

**Comment by IronOxidizer** [comment] 2021-07-20 22:45
Duplicate of https://github.com/IronOxidizer/Fast-as-Fabric/issues/7

**Closed as completed by IronOxidizer** 2021-07-20 22:45 UTC
Labels: duplicate
